modLoader="javafml"
loaderVersion="[1,)"
license="CC BY-NC-SA 4.0"

[[mods]]
modId="butchercrafttannery"
version="1.0.0"
displayName="Butchercraft: Tannery"
authors="Trollmonkey"
description='''
Addon for Butchercraft that adds hide scraping & tanning.
Requires Butchercraft.
'''

[[dependencies.butchercrafttannery]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.butchercrafttannery]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"

[[dependencies.butchercrafttannery]]
modId="butchercraft"
type="required"
versionRange="[2.6.4,)"
ordering="AFTER"
side="BOTH"