modLoader="javafml"
loaderVersion="[4,)"
license="CC-BY-NC-SA-4.0"

[[mods]]
modId="butchercrafttannery"
version="0.1.0"
displayName="Butchercraft Tannery"
authors="Trollmonkey"
description='''
Adds hide processing and tanning racks to integrate with Butchercraft.
'''

[[dependencies.butchercrafttannery]]
modId="neoforge"
type="required"
versionRange="[21.0.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.butchercrafttannery]]
modId="minecraft"
type="required"
versionRange="[1.21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.butchercrafttannery]]
modId="butchercraft"
mandatory=true
versionRange="[2.6.4,)"
ordering="AFTER"
side="BOTH"